name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # The name of the environment variable, not its value
          gpg-passphrase: OSSRH_GPG_PRIVATE_KEY_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Store tag name as version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set version
        run: mvn --batch-mode versions:set -DnewVersion=${{ env.RELEASE_VERSION }}

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_PRIVATE_KEY_PASSWORD }}
        run: |
          mvn --no-transfer-progress --batch-mode deploy